[package]
name = "rust-lapper"
version = "0.2.0"
authors = ["Seth Stadick <sstadick@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sstadick/basebits"
description = "A fast and easy library for interval overlap library"
documentation = "https://docs.rs/rust-lapper"
readme = "README.md"
categories = ["algorithms", "science"]
keywords = ["interval-tree", "intervaltree", "interval", "bioinformatics", "algorithm", "ranges", "overlap"]

[dependencies]
