[package]
name = "rust-lapper"
version = "0.2.2"
authors = ["Seth Stadick <sstadick@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sstadick/rust-lapper"
description = "A fast and easy library for interval overlap library"
documentation = "https://docs.rs/rust-lapper"
readme = "README.md"
categories = ["algorithms", "science"]
keywords = ["intervaltree", "interval tree", "bioinformatics", "genomic ranges", "interval-tree"]

[dependencies]
